//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourDuLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourDuLich
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Images { get; set; }
        public Nullable<double> NumOfDay { get; set; }
        public string LichDinhLy { get; set; }
        public string Address { get; set; }
        public Nullable<int> AmountOfPepople { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public int? idTinh { get; set; }
        public int? idLoaiTour { get; set; }
        public int? idMucGia { get; set; }

        public virtual LoaiTour LoaiTour { get; set; }
        public virtual MucGia MucGia { get; set; }
        public virtual TinhThanh TinhThanh { get; set; }
    }
}
